language: php
php:
  - 5.4
  - 5.5
before_script:
  - printf "\n" | pecl install -f imagick-3.1.2
  - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit